### ISSUE TITLE
Usar variáveis do css. 

### ISSUE THREAD

**Issue by JCDMeira** [viniciuslemos93/crud-produtos#3]
Assim estaria respeitando o princípio do one source of truth. Que presa a ideia de que só aja uma fonte da informação, e seria mais fácil mudar se achar necessário.

**Comment by viniciuslemos93** [comment]
Fala Jean! Certo, vou implementar sim, já usei em projetos anteriores variáveis no CSS, realmente a manutenção fica bem melhor, esta questão passou despercebida nesse projeto. Valeu!
